# -*- coding: GBK -*-


SVC_ID_UNKNOWN = 0x0000


SVC_ID_LOG = 0x0001
LOG_SVC_CMD_ID_LOGIN = 0x0001
LOG_SVC_CMD_ID_LOGOUT = 0x0002

SVC_ID_GAMEWORLD = 0x0002
GAMEWORLD_SVC_CMD_ID_ENTITY_STATE = 0x0001
GAMEWORLD_SVC_CMD_ID_ATTACK = 0x0002
GAMEWORLD_SVC_CMD_ID_BOARD = 0x0003


MSG_CS_LOGIN	= 0x1001
MSG_CS_CHARACTER_STATE	= 0x1002
MSG_CS_LOGOUT   = 0x1003
MSG_CS_ATTACK = 0x1004
MSG_CS_BOARD = 0x1005


MSG_SC_CHARACTER_STATE	= 0x2002
MSG_SC_CONFIRM	= 0x2001
MSG_SC_ENTITY_CREATION = 0x2003

NET_STATE_STOP	= 0				# state: init value
NET_STATE_CONNECTING	= 1		# state: connecting
NET_STATE_ESTABLISHED	= 2		# state: connected

NET_HEAD_LENGTH_SIZE	= 4		# 4 bytes little endian (x86)
NET_HEAD_LENGTH_FORMAT	= '<I'

NET_CONNECTION_NEW	= 0	# new connection
NET_CONNECTION_LEAVE	= 1	# lost connection
NET_CONNECTION_DATA	= 2	# data comming

NET_HOST_DEFAULT_TIMEOUT	= 70

MAX_HOST_CLIENTS_INDEX	= 0xffff
MAX_HOST_CLIENTS_BYTES	= 16

MAX_SERVER_ENTITIES_INDEX = 0xffff
MAX_SERVER_ENTITIES_BYTES = 16
